### ISSUE TITLE
Netherite Sowrds, ¿Which category?

### ISSUE THREAD

**Issue by Rouxshi** [PyvesB/advanced-achievements#984] opened 2021-03-18 19:06 UTC
:information_source: **Basic information**

* Advanced Achievements version:  7.0.1
* Minecraft version:  git-Paper-547 (MC: 1.16.5)
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read:   Yes.
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched:  Yes.
* Spigot username:  Rouxshi

:question: 

 I'm trying to create an achievement for crafting 100 netherite swords; ¿Which category should I use?, Tried with "Crafts" but not work, surely because the crafting table is not used for netherite sword.

:wrench: **Configuration**

````

````

**Comment by PyvesB** [comment] 2021-03-18 19:45
Hello @Rouxshi ! 👋🏻 

This seems like a duplicate of #781. 😉

**Closed** 2021-03-26 12:03 UTC
Labels: duplicate
