### ISSUE TITLE
Few neat things that could help tidy up the GUI

### ISSUE THREAD

**Issue by Tobi-Jakka** [PyvesB/advanced-achievements#907] opened 2020-12-18 04:21 UTC
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Read the open ones
* Spigot username: tobi224c

Hello,

first of all thanks for taking some time out your day to read this suggestion, not all plugin developers do that so it is very nice when a developer do, do it.

I have a few suggestions that I think could help improve the plugin. So far its very good but in a use case such as my own the GUI can get very messy. 

1. I have different tiers for my achievements & having them all displayed at once fills up the GUI very fast. Would it be possible to add a config option along the lines of "Hide-locked-tiers" which would hide tiers you have not yet gotten to (So lets say I have 6 tiers personally, if I am only at tier 1 I would only be able to see tier 1), this could get a bit confusing & therefor with a placeholder in the name it could make it easier to understand (like Break Stone - Tier 1/6 (1/6 would be the placeholder).

2. Well another config option. Would it be possible to add an option to hide the "menu block" (slot 0) when you open a category I think it looks weird especially when you have other achievements using the same block.

 
![image](https://user-images.githubusercontent.com/42676160/102574033-18f57400-40f0-11eb-800e-2f0820ce82b3.png)

I wish I could have simply made a contribution but I dont know how to write java so I guess there'd be no use in this. Though I'd be willing to make a donation if that'd help motivate you :)

- Tobi

**Comment by Tobi-Jakka** [comment] 2020-12-18 04:33
Not sure why I didnt think of this before but: A way to manually set in which slot the back button for each menu would be nice 👍

**Comment by PyvesB** [comment] 2020-12-18 19:30
Hello @Tobi-Jakka! 👋🏻 

Thanks for the feedback and suggestions!

1. Have you checked out the `HideProgressiveAchievements` configuration option? I believe that it _almost_ does what you want.

2. A couple of users have complained about this in the past if I remember correctly. The challenge here is that the block is actually useful to the GUI itself. When you have enough achievements in a given category, pagination kicks in with previous and next buttons. The plugin doesn't know which category the user is currently navigating through, and simply looks at the first item. Then it knows "I need to display page 2 of category X". It's not just a matter of implementing a trivial config option, the pagination logic needs to change, in other words to keep track of what the user has clicked on outside the GUI itself. But it's a reasonable ask, so I can give it a go!

3. Where would you rather see the back button?

**Comment by Tobi-Jakka** [comment] 2020-12-18 21:44
Hi, thanks for the quick reply!
So:

1. Sadly it is not what I was imagining as it simply replaces the block rather than removing it from the gui (picture below):
![image](https://user-images.githubusercontent.com/42676160/102664135-720de800-4182-11eb-9005-076b61923be5.png)

2. Sounds great! Thanks for being willing to give it a go, I'll definitely be looking forward to hearing how it went.

3. Depending I'd say middle of GUI as I assume the far left & right slots would be for pagination.

- Tobi

**Comment by PyvesB** [comment] 2020-12-19 15:43
Understood for number 3, that sounds like a good idea as well, will give it a go. I'm hoping I'll be pleased enough with how it looks to just change it wholesale for all users - too many configuration options can be overwhelming for some users and lead to more code complexity. :)

Will leave 1 to last as I suspect it will be the most involved. I'm wondering whether `HideProgressiveAchievements` needs to be reworked, the name after all is somewhat confusing, it's really "lock" rather than "hide".

**Comment by Tobi-Jakka** [comment] 2020-12-19 16:16
Okay thanks! Looking forward to an update :)

**Comment by PyvesB** [comment] 2020-12-19 17:17
> Okay thanks! Looking forward to an update :)

Don't hold you breath though, realistically this won't happen in what's left of 2020. As you can notice by looking at the `master` branch, I'm reorganising quite a lot of code in the plugin at the moment, so I'm warming up to the idea of a big 7.0.0 release, which will take longer to prepare! :)

**Comment by Tobi-Jakka** [comment] 2020-12-19 19:40
Well, I'll open up my server without the changes then, but that's fine! after all its just a matter of how the GUI look & then when 7.0.0 comes around, I can hopefully tidy up the GUI :) + I'm sure will bring other exciting features! 👍

**Comment by PyvesB** [comment] 2021-01-23 18:04
@Tobi-Jakka I'm finally found some time to start looking into this. I've come with two small variants:

1. Either the back button is the book (or whatever the user configured) for all achievement categories:
![2021-01-23_17 56 20](https://user-images.githubusercontent.com/10694593/105609960-9d4cae00-5da4-11eb-9ef1-983843dd2f49.png)

2. Either the back button is the category item:
![2021-01-23_18 02 22](https://user-images.githubusercontent.com/10694593/105610069-4a272b00-5da5-11eb-94ec-9b461fdf0b81.png)

What do you think? I'm personally more in favour of option 2, as it indicates more clearly which category the user is viewing.

Note that in the above screenshots, I've tweaked the GUI boundaries to start paginating with two full rows instead of five - couldn't be bothered to put craft a config with 45 achievements for the same category. Anything below 45 achievements, the previous and next buttons wouldn't appear. :)

**Comment by Tobi-Jakka** [comment] 2021-01-23 19:34
Yea, I definitely agree that having the back button be the category item would make it easy to remember which category you are viewing, though I think allowing people to display whatever item they want there would be better customization-wise. Not sure if you already did this, but I'd suggest not having a "previous page" button on the first page :p I know in some other plugins, example ShopGUI+ you can even configure which item should be used for "prev / next page" buttons...

I think in general it looks really clean so far I am definitely looking forward to this! :)
- Tobi

**Comment by PyvesB** [comment] 2021-01-24 11:04
> Yea, I definitely agree that having the back button be the category item would make it easy to remember which category you are viewing, though I think allowing people to display whatever item they want there would be better customization-wise

Done, a new `BackButtonIsCategoryItem` configuration option has been added.

>  Not sure if you already did this, but I'd suggest not having a "previous page" button on the first page :p

Done, same goes for the "next page" button on the last page. Putting the navigation items on a separate row made this much less of a headache code-wise!

> configure which item should be used for "prev / next page" buttons...

That's already been available for a while with configuration options in _gui.yml_. :)

**Comment by PyvesB** [comment] 2021-01-24 13:07
I've given the rework of `HideProgressiveAchievements` a spin, but I've not managed to make it work properly within a reasonable time frame. The current GUI code assumes that all achievements fill a slot in the GUI. Imagine you've got 180 achievements that fit into 4 GUI pages. When you're on page 4 and press on the previous button for example, the current functionality will display from the 91th to the 135th achievements. In a world where not all achievements are displayed, that doesn't work anymore, the code has to start from the 1st achievement all over again and figure out which achievements were and weren't displayed in pages 1 and 2 in order to build page 3 correctly. This would lead to more complex and less efficient code; unless you feel very strongly about this, I suggest we drop that part of the feature request.

**Comment by Tobi-Jakka** [comment] 2021-01-24 21:30
Hmm,

A question: So lets say its a tier based system. Which slot the different items are in are preset from config & would only be loaded on plugin reload. So whenever you get a new achievement, wouldn't the plugin just know where that specific achievement is placed & then update the name / description to display the info of the next tier?

Personally I feel very strongly about it, but as someone who happen to code myself I do not like the idea of inefficient code haha. Well I think this might work, but I'd like your input as someone who knows way more about coding plugins than I do :)

- Tobi

**Comment by PyvesB** [comment] 2021-01-24 21:45
> A question: So lets say its a tier based system. Which slot the different items are in are preset from config & would only be loaded on plugin reload. So whenever you get a new achievement, wouldn't the plugin just know where that specific achievement is placed & then update the name / description to display the info of the next tier?

The problem is that the GUI is generated dynamically on the fly - as such the GUI rendering engine is pretty much stateless. The inventories for individual players are not stored in the server's memory, so you can't update things when players get achievements for example. All the GUI code gets is "please render page 3 of category Breaks for player Y", and it then has to figure out what page 3 means in the context of that specific player. That's what makes things very hard when the GUI no longer contains a fixed number of achievements to display. :)

**Comment by Tobi-Jakka** [comment] 2021-01-27 23:58
Ah,

First of all sorry for the slow reply I saw the comment originally but had to think about it & might have forgotten to reply..
I definitely see the issue, but just so that I am sure we are talking about the same thing - If it can figure out what achievement a player have & dont have could it also not figure out which tier a player have that way ? Like when it tries to generate the tier 1 achievement if checks if it has that & then if so it places the tier 2 achievement instead (so that the amount of achievements in gui at once always stay the same some are just replaced depending on what the player have earned?

Not sure if this made any sense, I am not the best at explaning & you might have already pointed out why this wont work, just wanted to give it a shot at clearing up what I meant :)

- Tobi

**Comment by PyvesB** [comment] 2021-01-28 07:38
> the tier 1 achievement if checks if it has that & then if so it places the tier 2 achievement instead

I'm a bit confused by this frankly. In earlier messages you stated that "you would be able to see earlier tiers", the feature was intended as "Hide-locked-tiers which would hide tiers you have not yet gotten to". Placing just one tier at a time means that you would have just one achievement visible for the vast majority of categories, which defeats the point of the GUI.

**Comment by Tobi-Jakka** [comment] 2021-01-28 13:16
Oh so what I mean would be having only 1 tier visible from each type of achievement. So well this is probably just my own use case but I have a ton of different achievements, for example place x amount of stone, cobblestone, stonebricks, grass, sand, glass etc etc each have 6 tiers, so they spam the gui a ton where with only the tier your currently on visible pr different achievement they would not spam the gui as much*

**Comment by PyvesB** [comment] 2021-01-28 21:36
Okay, so we were clearly not on the same page. There are quite a few problems with the suggestion you've outlined in your last few messages:
* 44 of the 53 achievement categories do not support sub-categories, so would end up with just one achievement in each GUI page for a vast majority of categories. This would look odd aesthetically. It also makes the GUI pretty much useless: why make users click around an advanced inventory system if only a single piece of information is squeezed in the top left slot most of the time?
* data in other commands (/aach stats, /aach book, /aach top, etc.) will no longer match what is displayed in /aach list, as achievements will keep on disappearing from the GUI. This will be guaranteed confusion for your players. 
* players will no longer clearly know what achievements they've received. There will be no way for them to find past rewards. Similarly the only way they'll have left to get descriptions and reception dates will be tediously reading through their books.

If you're concerned with overloading the GUI for the few categories that do support subcategories, the only thing I can offer implementing is having each subcategory on a separate page, rather than all in the same page. That would be much better for players in my opinion. 😉

**Comment by Tobi-Jakka** [comment] 2021-01-29 12:53
Are I was talking more about these kind of sub categories
![image](https://user-images.githubusercontent.com/42676160/106277447-69a4d480-6239-11eb-89de-be34da413b11.png)

**Comment by PyvesB** [comment] 2021-01-29 15:06
Yes, I was talking about the same ones in the first bullet point. As indicated, there are only 9 such categories, the 44 others do not support sub-categories and would behave poorly with your suggestion. The two latter bullet point stand for all achievements categories though.

**Comment by Tobi-Jakka** [comment] 2021-02-03 08:21
Sorry for the late reply,

After some time I realised your point haha,
I was thinking a bit too much about the first "blocks placed" & the "block destroyed" categories...
But now that I think about it as you said, the other categories would not work that well with my suggestions, as they dont have as many sub categories, or in some cases only really 1 thing leaving the GUI empty...

- Tobi

**Comment by PyvesB** [comment] 2021-02-06 12:12
Glad to hear that we're on the same page!

For now I suggest trying out all the improvements that were made here and seeing what your players think after a few weeks. I can always give the one page per subcategory functionality I mentioned in https://github.com/PyvesB/advanced-achievements/issues/907#issuecomment-769415250 a try if need-be. In the meantime I'll close this issue. 😉

**Closed by PyvesB** 2021-02-06 12:12 UTC
Labels: enhancement
