### ISSUE TITLE
AdvancementsCompleted registering something that is not achievements

### ISSUE THREAD

**Issue by TheCashFire** [PyvesB/advanced-achievements#914] opened 2020-12-24 04:36 UTC
:information_source: **Basic information**

* Advanced Achievements version: <6.7.2 (premium version)>
* Minecraft version: <1.16.4>
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: <yes, does not appear the issue is documented>
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: <yes>

:beetle: **Description**

<Imagine a brand new server, as I have tested it many times this way. I have the config written up with many sections under the AdvancementsCompleted section of the file. Everything is written correctly, as I have run it and the plugin recognizes no errors. 

The issue is that when I log into the server, as a brand new player for each and every test I did (data files for all plugins wiped and everything), I did one mundane task, such as pick up a piece of stone, and I was awarded multiple levels of the AdvancementsCompleted tree (for stone, usually it would award me with +15 phantom achievements that would run the reward commands I have set for actually completing 15 achievements, rendering the entire system virtually useless as picking up a single piece of stone awards you many rewards for doing nothing). I am not sure why this occurs, it took me a couple horus to narrow the issue down myself, but I continued testing to see what would happen after picking up a piece of stone. It appeared that the more I progressed, such as chopping down a tree, mining a piece of coal, killing a pig and picking up porkchops, it would rack up completed achievements like crazy, even though I had not completed a single achievement I had written into the config file. It appears to award an achievement for each and every unlocked crafting recipe in the green inventory crafting recipe book, but that may just be me. If that is how it was intended to be, I was not aware and I apologize for this rushed bug report. I was planning to launch my server in two days time and I was shocked to discover something like this so late into my testing. I will eagerly await your reply, and can hop into discord and stream my issue if that will help.>

:page_facing_up: **Server logs**

<There are no logs, as the plugin does not read out any errors. There are only waves of unlocked achievements even though no achievements in the AdvancedAchievements file has been completed. Funny thing too, the plugin will even recognize that no achievements have been completed except for the AdvancementsCompleted ones that pop up. Strange huh?>

:wrench: **Configuration**

<Here is the entire config for Advancements Completed (as far as I know, there are no mistakes in here, but if Advancements is for some reason counting things not directly written into this config, im not entirely sure what the point of this section is. I beg you to help as fast as you can, I understand it is Christmas and I expect nothing. Thank you in advance, Happy Holidays.

AdvancementsCompleted:
  '5':
    Goal: §7Complete 5 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_5
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.rogue true
  '10':
    Goal: §7Complete 10 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_10
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.traveler true
  '15':
    Goal: §7Complete 15 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_15
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.citizen true
  '20':
    Goal: §7Complete 20 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_20
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.explorer true
  '25':
    Goal: §7Complete 25 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_25
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.adventurer true
  '30':
    Goal: §7Complete 30 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_30
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.merchant true
  '40':
    Goal: §7Complete 40 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_40
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.bard true
  '50':
    Goal: §7Complete 50 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_50
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.squire true
  '65':
    Goal: §7Complete 65 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_65
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.knight true
  '80':
    Goal: §7Complete 80 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_80
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.paladin true
  '100':
    Goal: §7Complete 100 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_100
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.crusader true
  '120':
    Goal: §7Complete 120 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_120
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.noble true
  '140':
    Goal: §7Complete 140 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_140
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.lord true
  '160':
    Goal: §7Complete 160 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_160
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.baron true
  '190':
    Goal: §7Complete 190 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_190
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.archon true
  '220':
    Goal: §7Complete 220 achievements.
    Message: §7You may progress to the next rank.
    Name: achievements_220
    DisplayName: §bRank Unlocked!
    Reward:
      Command:
        Execute: lp user PLAYER permission set role.royal true
>

**Comment by PyvesB** [comment] 2020-12-24 09:19
Hello @TheCashFire ! 👋🏻 

Sorry to hear things are not working as expected. This may be similar to #764. One common cause of confusion with the `AdvancementsCompleted` category is that it counts the number of **advancements** that a player receives. The word advancement, as opposed to achievements, is not used often in the plugin, but each time it is, it refers to the [Vanilla advancements](https://minecraft.gamepedia.com/Advancement) that were added in Minecraft 1.12.

By default, Spigot servers ship with a number of default advancements, Advanced Achievements will count those, which means you may have competed 10 or 20 Spigot advancements without having completed any of the plugin's achievements.

Does this help clarify things?

If you're just about to open your new server, you may simply want to delete Spigot's default advancements, I believe there is a configuration option in spigot.yml. 😉

**Comment by TheCashFire** [comment] 2020-12-24 15:15
Damn, I had expected this might be the case. If I remember correctly though, I have the modifier for the spigot advancements disabled using the tag minecraft:story disabled in the spigot.yml. Is there anothee way you know of off the top of your head to only count AdvancedAchievements instead of default ones? If I am able to only count AA ones that will solve this issue. I’ll check it when I get back to my computer too. Thanks for the quick reply, happy holidays!

**Comment by PyvesB** [comment] 2020-12-24 15:54
Try specifying the following in the _spigot.yml_:
```
advancements:
  disabled:
  - 'minecraft'
```

Apparently it's a new feature that was recently implemented in Spigot. See [here](https://hub.spigotmc.org/jira/plugins/servlet/mobile#issue/SPIGOT-6164) for more details.


> Thanks for the quick reply, happy holidays!

No worries, happy holidays to you too! 🍾

**Comment by TheCashFire** [comment] 2020-12-24 18:01
Just tried it. It did not work, the same issue occurs. As soon as I make something as simple as a crafting table, +17 achievements. Mine a coal ore, +6 achievments (or advancements, as far as minecraft is concerned). My entire ranking system is built off the back of being able to run a command allowing you to rank up once a specific amount of AdvancedAchievements have been completed, so if this does not work, do you have a better idea? That being said as well, is there a way of requesting this be a feature?

**Comment by TheCashFire** [comment] 2020-12-24 18:14
It appears that the default minecraft advancements are not the issue. I have just checked, they are disabled and regardless of that, crafting wooden planks gives +17 achievements, almost as if adding new recipes in your recipe book also counts as an advancement, even though I can't find a way to stop counting those.

**Comment by TheCashFire** [comment] 2020-12-24 19:30
Turns out, after some digging, there is a command that can be run to give yourself all advancements, namely

/advancement grant <name> everything

which will give you all advancements in the vanilla game. I tested this, and it indeed gave me every advancement; And in this case, I was right about the crafting. Turns out, each crafting recipe unlocked in the recipe book counts as an advancement, albeit a hidden one, giving a grand total of...

927 advancements.

![advencements](https://user-images.githubusercontent.com/60243600/103104069-d699ce80-45ea-11eb-9665-c5d42fa433c6.PNG)

So, this being the case, I may instead just use a real band-aid fix and automatically give every crafting recipe and vanilla advancement to the player upon login, bypassing the issue entirely (as there are no more advancements after you have been given them all, except for custom AA ones), and adding 927 to each of my values in my AdvancementsCompleted section of the config (this value would have to be changed for every MC version update that adds new blocks and hidden advancements though) . As AA does not count the vanilla advancements nor does it count the crafting ones, I believe this might be a workaround way to do it (if you are ok with new players having access to all crafting recipes from day one, which I am.) It will just be a matter of assigning that command to a player on first log in, and then using the gamerule announceAdvancements set to false to not spew messages in the chat.

I would request, though, that a section for only AdvancedAchievements be created though, as it would allow these two systems to work side by side instead of bricking one to use the other. Let me know what you think.

**Comment by PyvesB** [comment] 2020-12-25 08:37
> I would request, though, that a section for only AdvancedAchievements be created though, as it would allow these two systems to work side by side instead of bricking one to use the other. Let me know what you think.

Yes, if we can't get to the bottom of this, a new configuration option in the plugin can be added. :)

However, I'm keen on digging a bit further as I'm not convinced that Spigot is doing the right thing here. The code for this category in Advanced Achievements is really trivial:
```
@EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
public void onPlayerDoneAdvancement(PlayerAdvancementDoneEvent event) {
	updateStatisticAndAwardAchievementsIfAvailable(event.getPlayer(), 1);
}
```

According to your observations, even for recipes, the server is telling Advanced Achievements that an advancement was done. Searching through Spigot bugs, the following is related: https://hub.spigotmc.org/jira/browse/SPIGOT-5700

Each recipe indeed has an advancement associated with it. But one would expect that disabling all 'minecraft' advancements disables those as well. This seems like a bug to me, and I think we should report a new bug on the Spigot issue tracker. Would you like to take care of that?

**Comment by TheCashFire** [comment] 2020-12-25 19:08
I would agree, even having hidden crafting advancements, it would make sense that they should be disabled if you disable the root. How should I go about submitting this bug report? And where? First time bug-reporter here :P

Also, update on my solution, it actually worked. I used a plugin to automatically unlock all advancements on first join silently, then reset experience to 0 so the user would have no 
idea as it happens within 2 ticks. The only way you could tell that is because 1) all advancements are automatically unlocked in the advancements tree in the escape menu, which is easily taken care of by disabling it and 2) the amount of achievements tracker has an extra 927 values on it, giivng the indication that there are extra achievements unseen. Other than that though, it works great. Maybe that could be the simple true/false solution instead of adding an entirely seperate section? Just a simple modifier to toggle whether or not vanilla advancements are counted, and if they arent, remove that amount from the total for that section? Just a though.

**Comment by PyvesB** [comment] 2020-12-26 10:10
> I would agree, even having hidden crafting advancements, it would make sense that they should be disabled if you disable the root. How should I go about submitting this bug report? And where? First time bug-reporter here :P

You need to go [here](https://hub.spigotmc.org/jira/secure/Dashboard.jspa) and log in. A new account is possibly required, I don't remember if they allow your to reuse your Spigot account or not. Click on the Create button and fill in the details. Once you're done, share the ticket number here for reference :)

> Also, update on my solution, it actually worked. I used a plugin to automatically unlock all advancements on first join silently, then reset experience to 0 so the user would have no

Clever workaround! 👍🏻 

> Maybe that could be the simple true/false solution instead of adding an entirely seperate section? Just a simple modifier to toggle whether or not vanilla advancements are counted, and if they arent, remove that amount from the total for that section? Just a though.

Yes, I had a flag like that in mind as well. I'm hoping it's a last resort though, having less config and code complexity in Advanced Achievements is better! Also in terms of timelines, it wouldn't be immediate (see https://github.com/PyvesB/advanced-achievements/issues/907#issuecomment-748500422).

**Comment by TheCashFire** [comment] 2020-12-26 19:12
Well, turns out it doesn't work now for some reason. The AdvancementsCompleted section aparently does not count completed AdvancedAchievements Achievements at all, though I swear it did a few days ago. So I am out of ideas and will have to scrap this ranking system in favor of some other. Bummer.

I'll send in a ticket for it shortly.

**Comment by TheCashFire** [comment] 2020-12-27 17:08
https://hub.spigotmc.org/jira/browse/SPIGOT-6294

Ticket created.

**Comment by PyvesB** [comment] 2021-01-07 22:13
The issue you raised was marked as a duplicate of https://hub.spigotmc.org/jira/browse/SPIGOT-5885

Can you confirm whether runing _/minecraft:reload_ after startup solves the issue?

**Comment by PyvesB** [comment] 2021-01-29 20:49
As Spigot has essentially agreed that it's a big on their side and that there is a proposed workaround in the meantime, I'm gonna for ahead and close this. 😉

**Closed by PyvesB** 2021-01-29 20:49 UTC
Labels: bug
