### ISSUE TITLE
Message when inventory is full

### ISSUE THREAD

**Issue by JHarris12345** [PyvesB/advanced-achievements#1067] opened 2021-09-10 13:03 UTC
### 🚰 Spigot username

JHarris12345

### 📁 Existing issues

- [X] I have searched existing issues.

### 💡 Description

Is it possible for a console message to be outputted when the plugin tries to award someone items as a reward but their inventory is full? Right now, people just lose those items and it cant be logged if their inv was full or they're lying

**Comment by PyvesB** [comment] 2021-09-10 13:59
Hello @JHarris12345 ! :wave:

This feels pretty much like a duplicate of #1068 and #982.

**Closed by PyvesB** 2021-09-10 13:59 UTC
Labels: enhancement
