### ISSUE TITLE
Allow the definition of multiple custom achievement categories

### ISSUE THREAD

**Issue by VoxPopuliZombiemold** [PyvesB/advanced-achievements#987] opened 2021-03-21 16:35 UTC
:information_source: **Basic information**

* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes
* Spigot username: Zombiemold

:clipboard: **Description**

I'd love to see the ability to have multiple "custom" achievement categories for the custom achievement type.

I have seen another pull request that looks very complicated involving splitting achievements from their category, to allow for further customization, but that seems like a large challenge for this plugin.

Alternatively, I'd love to see the ability to simply define multiple "custom" achievement categories, with no coding required.

On our server, we utilize the custom category heavily. The custom category obviously allows for tons of cross-plugin compatibility via command usage. It's really nifty. However, our custom category is getting filled up with lots of achievements that don't really "fit" together. It'd be cool if I could define multiple "custom" achievement categories, and nest the custom achievements in each of these categories for better organization, and clarity of use. 

Thanks 👍 

![javaw_2021-03-21_09-34-55](https://user-images.githubusercontent.com/3165706/111912861-c1391280-8a28-11eb-87d7-95d0bcdae36d.png)

**Comment by PyvesB** [comment] 2021-03-22 12:17
Hello @VoxPopuliZombiemold ! 👋🏻 

This essentially sounds like a duplicate of #536, #896 and possibly one or two others others. It's something that's been requested occasionally over the years, but not very often. As it's quite involved, other contributors or myself have not yet gotten round to looking into it.

> However, our custom category is getting filled up with lots of achievements that don't really "fit" together. It'd be cool if I could define multiple "custom" achievement categories, and nest the custom achievements in each of these categories for better organization, and clarity of use.

Two thing which I can suggest to improve this:
* use different `Type` parameters for the different sub-categories. The default config uses `normal` and `rare` as examples, but you can pick any values you want to assign to whatever achievements you want. This way, even if the achievements are together in the GUI, they will be grouped visually by items.
* display each sub-category in a separate page which you would access with the "Next"/"Previous" buttons. This is not yet possibly, but I could probably implement this in a more reasonable time frame. This should further help with organization and clarity. What do you think?

**Closed** 2021-04-12 08:13 UTC
Labels: general support
