### ISSUE TITLE
Customizability

### ISSUE THREAD

**Issue by Omegus711** [PyvesB/advanced-achievements#1037] opened 2021-06-20 16:12 UTC
**Spigot Username:**
taylorfin16

**Description:**
Hey so some of the plugin's features are really fixed and not very customizable. I'd like it if we could do all of these things in future, it would make the plugin perfect:

Be able to format the achievements menu any way by changing achievement slot numbers or adding in an item with the slot ID -1 to fill in the empty gaps with glass panes.

![image](https://user-images.githubusercontent.com/69909546/122681086-9195d400-d1ea-11eb-9f77-1598d23b7424.png)

Being able to create new, custom categories with full menu formatting for each category and being able to choose which slot they go into in the main achievement menu.
![image](https://user-images.githubusercontent.com/69909546/122680865-57780280-d1e9-11eb-8b5f-2e0443cfec50.png)
![image](https://user-images.githubusercontent.com/69909546/122680970-ebe26500-d1e9-11eb-8433-13692fdb5997.png)

Fully customizable lore for achievements:

list-description: "Description:"
list-goal: "Goal:"
list-reception: "Reception date:"

**(symbol is the checkmark or the cross)**
title: "%symbol% %achievement_name%"
- ""
- "Description:"
- "%description%"
- ""
- "Reception date:"
- "%date%"

I apologize if this is too much, but seeing as this is the only achievement plugin on spigot it'd mean the world to me and surely to many others. Thanks for reading :D

**Comment by Omegus711** [comment] 2021-06-20 16:13
Existing Categories would be preconfigured in mainmenu.yml

**Comment by Omegus711** [comment] 2021-06-20 16:14
Oh also for the "back" button, I'd like that to be in each category's config too:

Back:
  DisplayName: "Back"
  Material: iron_door
  Slot: 25

**Comment by PyvesB** [comment] 2021-06-21 18:48
Hello @Omegus711! 👋🏻 

As in #825, I note that you've ignored the issue templates. In particular, the step "[Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched" would have probably pointed out that this is by and large a duplicate of other existing issues. Unless there's anything in particular you wanted to highlight, I'm keen on closing this. 😉

**Comment by Omegus711** [comment] 2021-06-21 20:09
> Hello @Omegus711! 👋🏻
> 
> As in #825, I note that you've ignored the issue templates. In particular, the step "[Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched" would have probably pointed out that this is by and large a duplicate of other existing issues. Unless there's anything in particular you wanted to highlight, I'm keen on closing this. 😉

I'm sure I used the correct format, but I'm probably wrong.

You're free to close it but I'm hopeful this could be added in the future.

**Comment by PyvesB** [comment] 2021-06-26 09:58
Okay, will close. I suggest subscribing to #990, that's the core piece of work that will allow the "being able to create new, custom categories" feature you mentioned.

**Closed by PyvesB** 2021-06-26 09:58 UTC
