### ISSUE TITLE
Help with currency sign and completion tick sign

### ISSUE THREAD

**Issue by SirCraftypants** [PyvesB/advanced-achievements#815] opened 2020-08-03 19:27 UTC
:information_source: **Basic information**

* Advanced Achievements version: 6.1.3
* Minecraft version: 1.15.2 
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: yes

:question: **Help request**

I'm using Vault and EssentialsX and my currency is set to (c) Coins
Is there a way I can add my Currency symbol to money: 1 i.e. money: 1c or money: 1 coin

And where can i find the completion tick so i can edit it as right now it's just a thick line of green not resembling a tick, more a horizontal dash.

Thanks

**Comment by SirCraftypants** [comment] 2020-08-04 08:17
Right now it just says 

reward:
      receive: 2

with a strange icon just before receive: 2

**Comment by SirCraftypants** [comment] 2020-08-04 08:21
I also have a great idea

Allow admin to right click an achievement of anyone player to reset it.

**Comment by PyvesB** [comment] 2020-08-04 21:32
Hi @SirCraftypants,

This looks like a duplicate of #586, please let me know if I'm wrong. :)

**Comment by SirCraftypants** [comment] 2020-08-04 21:51
> 
> 
> Hi @SirCraftypants,
> 
> This looks like a duplicate of #586, please let me know if I'm wrong. :)

Hi, Yes and No, yes it's solved my Currency question so thank you for that.

The completion Tick is just a thick horizontal line and the icons before each reward are odd looking like an alien language, difficult to describe..

**Comment by PyvesB** [comment] 2020-08-05 07:50
The completion ticks can be changes through this parameter in _lang.yml_: https://github.com/PyvesB/AdvancedAchievements/blob/efbc3dd25e59d3847b73abc9174f3b9536c8d4b5/advanced-achievements-plugin/src/main/resources/lang.yml#L135

I'm guessing you've ended up with an encoding problem of some sort.

**Comment by SirCraftypants** [comment] 2020-08-23 16:47
Is there a way you could make it so that it's within the config in a future update. Just if i extract, change and reupload, when i go to update later on it will return to default.?

**Comment by PyvesB** [comment] 2020-08-23 16:57
Making it a config option is probably the best long term solution. I probably won't be able to commit to it in the coming days/weeks though, but any one else is welcome to submit a pull request as well. :)

**Comment by PyvesB** [comment] 2020-10-02 20:58
Will close in favour of #858, which would allow to customise the dots as well. 😉

**Closed by PyvesB** 2020-10-02 20:58 UTC
Labels: general support
