### ISSUE TITLE
Items drop on floor if inv is full

### ISSUE THREAD

**Issue by JHarris12345** [PyvesB/advanced-achievements#982] opened 2021-03-16 14:26 UTC
:information_source: **Basic information**

* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched:  Yes
* Spigot username:  JHarris12345

:clipboard: **Description**
Currently if you win an item reward whilst your inv is full, you lose it. I think there should be an option to let the items drop on the floor

**Comment by PyvesB** [comment] 2021-03-16 19:19
Hello @JHarris12345 ! 👋🏻 

This is pretty much a duplicate of  #720. If you're convinced your setup is correct on your side and there's something wrong with Advanced Achievements, please:
* provide detailed steps on how to reproduce when no other plugin is installed on the server. A video would be helpful.
* provide information about your server, as is requested in the default issue templates: Minecraft version, type of server (Spigot? Paper? something else?), etc.

**Comment by PyvesB** [comment] 2021-04-01 17:32
Any news on this issue @JHarris12345 ? :)

**Comment by PyvesB** [comment] 2021-04-18 10:58
It's been over a month, will close. Feel free to reopen if/when you're able to provide the information requested above. 😉

**Closed by PyvesB** 2021-04-18 10:58 UTC
Labels: cannot reproduce, duplicate
