### ISSUE TITLE
Advancement Placement

### ISSUE THREAD

**Issue by SpyroDraconica** [PyvesB/advanced-achievements#969] opened 2021-03-03 22:11 UTC
:information_source: **Basic information**

* Advanced Achievements version: 7.0.0
* Minecraft version: 1.16.3
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes

:question: **Help request**

Ok so, My plan is making a custom category (in the vanilla advancement UI) Where I have An achievement, when you get said achievement, it will show the next one(s) BUT there are 5(or more) of them that spit off from the first one, where out of one of them there shows another achievement behind it, which splits into more again. Ect, Etc.
now... How do I make a completely new category(and change the book texture)? How do I make it so there is an advancement AFTER another and how do I make the achievement tree split up into more? 
I have looked at the files, at the wiki and more and don't seem to find any actual information on the way you place the achievements in the achievement tree the way I want.
Note that all of the achievements that this achievement tree will only be obtained by the /aach give command.
(if possible also give info on how I can sort the achievement that slit off from the previous one) 

(The splitting into more achievements and then splitting again can be seen in 'The End' tab from vanilla for an example of what I am trying to do, In this case it's 1 achievement, then another one, after that it splits into 4, then one of them has another achievement after it which splits into two once again)

(Exact plan: New category will show up when you get the first achievement, This achievement will show 5 more all of them exept one will not show any more after, but the middle one will show the next achievement after it which on completion will show 5 achievement again like the one of before, repeat this splitting and taking the middle one to split again like 20 more times[Category will have a stone brick as item and the background is cracked stone bricks)

[I am sorry if these questions has been asked before but after a few hours of not finding any info... you can imagine that I kinda want to end it here and just make a ticket.]

Thank you.
- Spyro

**Comment by PyvesB** [comment] 2021-03-04 09:35
Hello @SpyroDraconica ! 👋🏻 

This pretty much seems like a duplicate of #939, does that issue help?

**Comment by PyvesB** [comment] 2021-03-11 09:21
I've also improved [the Wiki](https://github.com/PyvesB/advanced-achievements/wiki/Commands) to make things clearer and avoid further duplicates. 😉

**Closed by PyvesB** 2021-03-11 09:21 UTC
Labels: general support
