### ISSUE TITLE
Request Boss plugin Support

### ISSUE THREAD

**Issue by BobbyMere** [PyvesB/advanced-achievements#842] opened 2020-09-13 09:25 UTC
* [x] AA v6.2.1
* [x] MC v1.16.2 paper
* [x] Read through Wiki
* [x] Not really an existing issue

Since this plugin is now paid premium, would you add Boss plugin support now, please?

**Comment by PyvesB** [comment] 2020-09-14 06:55
Hi @BobbyMere,

Duplicate of #623, closing this one as there's little point in having multiple issues about the same feature request. :wink:

**Closed by PyvesB** 2020-09-14 06:55 UTC
